
export declare enum EventUser {
    CONNECT = 'AUTHENTIFICATION',
    DECONNECT= "DECONNECTER",
    TENTATIVE_CON= "TENTATIVE_CONNECTION",
    TENT= "TENTATIVE_CONNECTION",
    CREATE= "CREATION",
    UPDATE= "MODIFICATION",
    DELETE= "SUPPRESSION",
    CHAT= "CHAT"
}